language: go

before_install:
  - go get code.google.com/p/gorest
  - go get labix.org/v2/mgo

install:
  - mkdir -p $GOPATH/src/github.com
  - mv $HOME/build/jmadan $GOPATH/src/github.com/
  - cd $GOPATH/src/github.com/jmadan/go-msgstory
  - go build -v